### ISSUE TITLE
Support latest graphql version?

### ISSUE THREAD

**Issue by adampash** [smooth-code/graphql-directive#2]
I've noticed some issues if I'm using this with the latest `graphql` (0.12.3). If I try using it on a schema, the first error I get is:

`Uncaught TypeError: Cannot read property 'FIELD_DEFINITION' of undefined`

Which is coming from [here](https://github.com/smooth-code/graphql-directive/blob/master/src/addDirectiveResolveFunctionsToSchema.js#L57). It seems that the latest `graphql` has updated some of the object mappings. (Seems like there are [a lot of updates to the schema](https://github.com/graphql/graphql-js/releases/tag/v0.12.0) in 0.12.)

**Comment by gregberge** [comment]
Thanks for reporting it! Looks like they are moving forward in this direction, they now exposed some internal functions. I made a PR but I would like to support v0.11 and v0.12, would do it soon. Feel free to point on my PR if you want to use it before releasing.

**Comment by adampash** [comment]
Oh yeah, I just realized `graphql-tools` has added an `attachDirectiveResolvers`. I'll probably just use that for now, then, for the newer `graphql` package. Thanks for this, though!

**Comment by gregberge** [comment]
@adampash yes you can use it but it will not support directives in queries.

**Comment by gregberge** [comment]
[version 0.2.0](https://github.com/smooth-code/graphql-directive/releases/tag/v0.2.0) supports `graphql@^0.11` and `graphql@^0.12`.
